"""create inital tablesss

Revision ID: e8cd19d36e98
Revises: 9d7cc64c2003
Create Date: 2023-06-13 21:10:44.704797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8cd19d36e98'
down_revision = '9d7cc64c2003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostics_id'), 'diagnostics', ['id'], unique=False)
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('diag_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=300), nullable=True),
    sa.Column('method', sa.String(length=300), nullable=True),
    sa.Column('specimen', sa.String(length=300), nullable=True),
    sa.Column('specimen_vol', sa.String(length=300), nullable=True),
    sa.Column('run_days', sa.String(length=300), nullable=True),
    sa.Column('tat', sa.String(length=300), nullable=True),
    sa.Column('instructions', sa.String(length=300), nullable=True),
    sa.Column('mrp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['diag_id'], ['diagnostics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tests_id'), 'tests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tests_id'), table_name='tests')
    op.drop_table('tests')
    op.drop_index(op.f('ix_diagnostics_id'), table_name='diagnostics')
    op.drop_table('diagnostics')
    # ### end Alembic commands ###
